### ISSUE TITLE
feature request, date filter

### ISSUE THREAD

**Issue by Tigwin** [FarisHijazi/Rarbg-Enhancer-UserScript#24]
Great script! Just wanted to ask if its possible for you to add a date filter. e.g; Hide or gray out items older than X hours old? That way if I check for files once a week, or once a day, I can set it to show me when to stop browsing.

**Comment by FarisHijazi** [comment]
Thanks!
I'll be happy if you submit a PR, but won't this just work if you just sort by date? I don't want to add things to filter things out because the amount of features needed would be huge, and making search filters would be complex
let me know how much this is needed, and if so, I'd appreciate a contribution
