### ISSUE TITLE
Download Batch torrents as a zip

### ISSUE THREAD

**Issue by leonard4546** [FarisHijazi/Rarbg-Enhancer-UserScript#3]
Hello. Thanks for this script. is it possible to add zip functionality in batch downloader. I have seen this function in script of some other site. it will also help to avoid load on browser due to multiple download spam.

**Comment by FarisHijazi** [comment]
Yes it is possible and i have zip functions, lemme take a look at that later

**Comment by FarisHijazi** [comment]
I looked into it, and the zip files aren't working nicely with rarbg due to the fact that some torrents will actually go to an html page, I advise that you stick to that, I could do something for you which is add a delay between the downloads, but what I'm saying is: zipping will introduce new issues and they will be invisible as you won't realize that you have torrents missing

if you want to download them as a file, press `ctrl+s`, this will download a compact html file, as well as a .json file
